package com.example.dev22.fragmentsexample.databases;


public interface Database {

    String DATABASE_NAME = "db.sqlite";

    int DATABASE_VERSION = 1;

    String QUERY_ENABLE_FOREIGN_KEYS = "PRAGMA foreign_keys=ON;";

    String TABLE_ALUNO = "ALUNO",
           FIELD_TABLE_ALUNO_CODIGO = "CODIGO",
           FIELD_TABLE_ALUNO_NOME = "NOME",
           FIELD_TABLE_ALUNO_ENDERECO = "ENDERECO",
           FIELD_TABLE_ALUNO_NUMERO = "NUMERO",
           FIELD_TABLE_ALUNO_CEP = "CEP",
           FIELD_TABLE_ALUNO_CIDADE = "CIDADE",
           FIELD_TABLE_ALUNO_ESTADO = "ESTADO",
           FIELD_TABLE_ALUNO_COMPLEMENTO = "COMPLEMENTO";

    String QUERY_CREATE_TABLE_ALUNO = "CREATE TABLE IF NOT EXISTS " + TABLE_ALUNO + " ( " +
           FIELD_TABLE_ALUNO_CODIGO + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
           FIELD_TABLE_ALUNO_NOME + " TEXT NOT NULL, " +
           FIELD_TABLE_ALUNO_ENDERECO + " TEXT, " +
           FIELD_TABLE_ALUNO_NUMERO + " TEXT, " +
           FIELD_TABLE_ALUNO_CEP + " TEXT, " +
           FIELD_TABLE_ALUNO_CIDADE + " TEXT, " +
           FIELD_TABLE_ALUNO_ESTADO + " TEXT, " +
           FIELD_TABLE_ALUNO_COMPLEMENTO + " TEXT)";

    String QUERY_DROP_TABLE_ALUNO = "DROP TABLE IF EXISTS " + TABLE_ALUNO;

    String TABLE_PROFESSOR = "PROFESSOR",
           FIELD_TABLE_PROFESSOR_CODIGO = "CODIGO",
           FIELD_TABLE_PROFESSOR_NOME = "NOME",
           FIELD_TABLE_PROFESSOR_USUARIO = "USUARIO",
           FIELD_TABLE_PROFESSOR_SENHA = "SENHA",
           FIELD_TABLE_PROFESSOR_ENDERECO = "ENDERECO",
           FIELD_TABLE_PROFESSOR_EMAIL = "EMAIL",
           FIELD_TABLE_PROFESSOR_NUMERO = "NUMERO",
           FIELD_TABLE_PROFESSOR_CEP = "CEP",
           FIELD_TABLE_PROFESSOR_CIDADE = "CIDADE",
           FIELD_TABLE_PROFESSOR_ESTADO = "ESTADO",
           FIELD_TABLE_PROFESSOR_COMPLEMENTO = "COMPLEMENTO";

    String QUERY_CREATE_TABLE_PROFESSOR = "CREATE TABLE IF NOT EXISTS " + TABLE_PROFESSOR + " ( " +
           FIELD_TABLE_PROFESSOR_CODIGO + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
           FIELD_TABLE_PROFESSOR_NOME + " TEXT NOT NULL, "  +
           FIELD_TABLE_PROFESSOR_USUARIO + " TEXT NOT NULL, " +
           FIELD_TABLE_PROFESSOR_SENHA + " TEXT NOT NULL, " +
           FIELD_TABLE_PROFESSOR_ENDERECO + " TEXT, " +
           FIELD_TABLE_PROFESSOR_EMAIL + " TEXT NOT NULL, " +
           FIELD_TABLE_PROFESSOR_NUMERO + " TEXT, " +
           FIELD_TABLE_PROFESSOR_CEP + " TEXT, " +
           FIELD_TABLE_PROFESSOR_CIDADE + " TEXT, " +
           FIELD_TABLE_PROFESSOR_ESTADO + " TEXT, " +
           FIELD_TABLE_PROFESSOR_COMPLEMENTO + " TEXT)";

    String QUERY_DROP_TABLE_PROFESSOR = "DROP TABLE IF EXISTS " + TABLE_PROFESSOR;

    String TABLE_MATERIA = "MATERIA",
           FIELD_TABLE_MATERIA_CODIGO = "CODIGO",
           FIELD_TABLE_MATERIA_NOME = "NOME",
           FIELD_TABLE_MATERIA_PROFESSOR = "PROFESSOR",
           FIELD_TABLE_MATERIA_DESCRICAO = "DESCRICAO";

    String QUERY_CREATE_TABLE_MATERIA = "CREATE TABLE IF NOT EXISTS " + TABLE_MATERIA + " (" +
           FIELD_TABLE_MATERIA_CODIGO + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
           FIELD_TABLE_MATERIA_NOME + " TEXT NOT NULL, " +
           FIELD_TABLE_MATERIA_DESCRICAO + " TEXT, " +
           FIELD_TABLE_MATERIA_PROFESSOR + " INTEGER NOT NULL, " +
           "FOREIGN KEY (" + FIELD_TABLE_MATERIA_PROFESSOR + ") REFERENCES " + TABLE_PROFESSOR +
           "(" + FIELD_TABLE_PROFESSOR_CODIGO + "))";

    String QUERY_DROP_TABLE_MATERIA = "DROP TABLE IF EXISTS " + TABLE_MATERIA;

    String TABLE_NOTA = "NOTA",
           FIELD_TABLE_NOTA_CODIGO = "CODIGO",
           FIELD_TABLE_NOTA_ALUNO = "ALUNO",
           FIELD_TABLE_NOTA_MATERIA = "MATERIA",
           FIELD_TABLE_NOTA_NOTA1 = "NOTA1",
           FIELD_TABLE_NOTA_NOTA2 = "NOTA2",
           FIELD_TABLE_NOTA_NOTA3 = "NOTA3",
           FIELD_TABLE_NOTA_NOTA4 = "NOTA4",
           FIELD_TABLE_NOTA_FALTAS = "FALTAS";

    String QUERY_CREATE_TABLE_NOTA = "CREATE TABLE IF NOT EXISTS " + TABLE_NOTA + " (" +
           FIELD_TABLE_NOTA_CODIGO + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
           FIELD_TABLE_NOTA_NOTA1 + " REAL, " +
           FIELD_TABLE_NOTA_NOTA2 + " REAL, " +
           FIELD_TABLE_NOTA_NOTA3 + " REAL, " +
           FIELD_TABLE_NOTA_NOTA4 + " REAL, " +
           FIELD_TABLE_NOTA_FALTAS + " INTEGER, " +
           FIELD_TABLE_NOTA_MATERIA + " INTEGER NOT NULL, " +
            FIELD_TABLE_NOTA_ALUNO + " INTEGER NOT NULL, " +
           "FOREIGN KEY (" + FIELD_TABLE_NOTA_MATERIA + ") REFERENCES " + TABLE_MATERIA +
           "(" + FIELD_TABLE_MATERIA_CODIGO + "), " +
           "FOREIGN KEY (" + FIELD_TABLE_NOTA_ALUNO + ") REFERENCES " + TABLE_ALUNO +
           "(" + FIELD_TABLE_ALUNO_CODIGO + "))";

    String QUERY_DROP_TABLE_NOTA = "DROP TABLE IF EXISTS " + TABLE_NOTA;






}
